# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.IntegerField()),
                ('requested_to', models.IntegerField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved')], default='p', max_length=1)),
                ('prescription_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('d', 'doctor'), ('p', 'patient'), ('m', 'pharmacist')], default='p', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.UserProfile'),
        ),
    ]
